version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finance-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finance-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app/frontend
    restart: always
    depends_on:
      - backend


