version: '3.8'

services:
  backend:
    build: ./backend
    container_name: finance-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: finance-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: always
    depends_on:
      - backend


